mlr: completing R analysis and adapting examples (also fixing old paje_summary mistake)

diff --git a/tools/starpu_mlr_analysis.in b/tools/starpu_mlr_analysis.in
--- a/tools/starpu_mlr_analysis.in
+++ b/tools/starpu_mlr_analysis.in
@@ -2,8 +2,7 @@
 
 # StarPU --- Runtime system for heterogeneous multicore architectures.
 # 
-# Copyright (C) 2014  Université Joseph Fourier
-# Copyright (C) 2014-2015  Université Bordeaux
+# Copyright (C) 2016  Inria
 # 
 # StarPU is free software; you can redistribute it and/or modify
 # it under the terms of the GNU Lesser General Public License as published by
@@ -21,9 +20,10 @@
 set -e # fail fast
 
 # File names
-basename="$PWD"
+SOURCE_DIR=@abs_srcdir@
+
 outputfile="mlr_analysis.html"
-analysis_script="$(dirname $(which $0))/starpu_mlr_analysis.Rmd"
+analysis_script="$SOURCE_DIR/starpu_mlr_analysis.Rmd"
 
 # Command line arguments
 inputfile=""
@@ -31,13 +31,14 @@ inputfile=""
 help_script()
 {
 cat << EOF
-Give statistical analysis of the paje trace
+Give an example of the trace analysis for computing multiple linear regression model
 
 Options:
    -h      Show this message
 
 Examples:
 $0 .starpu/sampling/codelets/tmp/test_mlr.out
+$0 
 
 Report bugs to <@PACKAGE_BUGREPORT@>
 EOF
@@ -48,13 +49,13 @@ if [ "$1" = "--version" ] ; then
     exit 0
 fi
 
-if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ "$1" = "" ] ; then
+if [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
     help_script
     exit 0
 fi
 
 while getopts "h" opt; do
-  case $opt in
+    case $opt in
     \?)
       echo "Invalid option: -$OPTARG"
       help_script
@@ -66,12 +67,22 @@ done
 # Reading files that need to be analyzed
 shift $((OPTIND - 1))
 inputfile=$1
-# Error if there is no input files specified
-# if [[ $# != 1]]; then
-#     echo "Error!"
-#     help_script
-#     exit 2
-# fi
+if [[ $# < 1 ]]; then
+    inputfile="$SOURCE_DIR/perfmodels/sampling/codelets/tmp/mlr_init.out"
+else
+# Error if there is more than one input file
+    if [[ $# > 1 ]]; then
+	echo "Error!"
+	help_script
+	exit 2
+    fi
+fi
+
+if [ ! -s $inputfile ]
+    then
+	echo "Error: file $inputfile does not exist!"
+	exit 5
+fi
 
 #####################################
 # Running analysis file to get actual results
